metadata.json
Push any backports of 2.x to the `puppet3` branch.
=> The puppet 4-only release will start at 3.0.0

manifests/config.pp
Depending on the default ownership and permissions of the Puppet run, the
configuration might be unreadable by the grafana user, causing the service
startup to fail.
One such possible cause is if the file type has default permissions such as:
```
File {
owner => 'root',
group => 'root',
mode  => '0600',
}
```
=> FIX configuration file ownership

lib/puppet/provider/grafana_dashboard/grafana.rb, lib/puppet/type/grafana_dashboard.rb
This fixes #25, while also fixing syntax errors of some API requests and implements idempotency.
=> Fix grafana_dashboards

manifests/install.pp, spec/classes/grafana_spec.rb
we can't pass the grafana version to the archlinux package provider. it
has no versionable feature. this adds a workaround to provide 'present'
to it. This can later be extended to pass explicit states to the other
operating systems as well, or to implement ensure=>absent. We can't set
the $version variable to 'present' because this will kill the other
installation methods.
=> implement package_ensure param for archlinux

manifests/install.pp, manifests/params.pp, spec/classes/grafana_spec.rb
We should use the repository by default to get updates automatically.
=> Debian and RedHat based operating systems should use the repository by default

manifests/install.pp, spec/classes/grafana_spec.rb
After trying to set up grafana on Ubuntu 14.04 using this module, I noticed the `apt::source` is configured with `$::lsbdistcodename`, which creates a broken source file (`deb https://packagecloud.io/grafana/stable/debian trusty main` returns a 404). The [grafana docs](http://docs.grafana.org/installation/debian/) states `deb https://packagecloud.io/grafana/stable/debian/ jessie main` should be used.
> Even if you are on Ubuntu or another Debian version, according to docs.grafana.org/installation/debian.
>
=> Always use jessie apt repo when osfamily is Debian.

README.md, lib/puppet/type/grafana_datasource.rb, manifests/plugin.pp, spec/defines/plugin_spec.rb
this got tested with the example from the README and works fine.
=> Support custom plugins

lib/puppet/provider/grafana.rb
This appears to have been broken since the initial commit in 3e672bb32b163b697a67a5936703c7dcd17a77dd.
Ether typo should be fixed or redundant predicate removed.
=> Fix typo in provider

.sync.yml, .travis.yml, Gemfile, README.md, manifests/init.pp, manifests/install.pp, manifests/params.pp, metadata.json, spec/acceptance/class_spec.rb, spec/classes/grafana_spec.rb, spec/spec_helper_acceptance.rb
This PR
- Sets the default Grafana version to 4.5.1. It still leaves the version hard-coded and not set to latest since 2 of the three intallation methods rely on it. The previous configuration did not work on newer systems with default settings.
- Gets rid of anchor pattern and uses `contain()` to declare the classes.
- Sets acceptance tests to run (on CentOS 7 and Ubuntu 16.04) in Travis
- Reworks spec_helper_acceptance
- Adds support for CentOS / RedHat 7, Ubuntu 16.04, and bumps metadata, makes apt and docker  soft dependencies per style guide.
Ran acceptance tests locally for Ubuntu 14.04 and CentOS 6 as well.
=> BREAKING: Update default Grafana version to 4.5.1 and improve acceptance tests

.fixtures.yml, manifests/install.pp, metadata.json, spec/classes/grafana_spec.rb
Module already has puppet-archive as a dependency, and seems like this is preferable anyway
=> Get rid of the dependency on 'wget' module in favor of puppet-archive

manifests/init.pp, manifests/params.pp, spec/classes/grafana_spec.rb
This switches the module to Puppet data types.
=> BREAKING: Switch to Puppet Data Types (ldap_cfg is now undef when disabled)

lib/puppet/provider/grafana.rb, lib/puppet/provider/grafana_dashboard/grafana.rb, lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/provider/grafana_user/grafana.rb, lib/puppet/type/grafana_dashboard.rb, lib/puppet/type/grafana_datasource.rb, lib/puppet/type/grafana_user.rb
I think these aren't needed, since the license is already included in the project, thoughts?
=> Remove licenses from the top of files

CHANGELOG.md, HISTORY.md, metadata.json
=> Release 4.0.0

metadata.json
This just fixes a minor typo with RedHat 6 being there twice but 7 not at all.
=> fix typo in metadata (redhat 6 twice vs 6/7)

README.md
I just used the approach described in the issue https://github.com/voxpupuli/puppet-grafana/issues/35 about using `http_conn_validator` to check if Grafana is up and running before the creation of a Datasource and it took me no time to update the README file with some examples.
=> Update readme with examples of using datasource and dashboard

README.md, lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/provider/grafana_organization/grafana.rb, lib/puppet/type/grafana_datasource.rb, lib/puppet/type/grafana_organization.rb, spec/unit/puppet/type/grafana_datasource_type_spec.rb, spec/unit/puppet/type/grafana_organization_type_spec.rb
- Updated grafana datasource provider to allow datasources to be created
on specific organizations
- Added grafana organization provider to allow organizations to be
created
- Updated README to add more descriptive information for previous
features as well as new
Fixes commercial/enterprise-meta#91
SIMP-4206 #close
=> (SIMP-4206) Added organization provider and updated datasource provider

lib/puppet/provider/grafana_datasource/grafana.rb
with_credentials def was referencing datasource[:is_default] and
preventing idempotency
=> fix datasource provider error

README.md, lib/puppet/provider/grafana_dashboard/grafana.rb, lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/provider/grafana_organization/grafana.rb, lib/puppet/provider/grafana_user/grafana.rb, lib/puppet/type/grafana_dashboard.rb, lib/puppet/type/grafana_datasource.rb, lib/puppet/type/grafana_organization.rb, lib/puppet/type/grafana_user.rb
- Updated types and providers to allow the grafana_api_path parameter to
be set when using sub-paths for the API
=> Add grafana_api_path to allow for API sub-paths

README.md, lib/puppet/provider/grafana_dashboard/grafana.rb, lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/provider/grafana_organization/grafana.rb, lib/puppet/type/grafana_dashboard.rb, lib/puppet/type/grafana_datasource.rb
For request #48 "add `organization` param to grafana_dashboard resource".
Also fixes syntax error where 'org_name' was used instead of 'organization' in the README
=> Expand organization property for dashboards

README.md, lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/type/grafana_datasource.rb, spec/unit/puppet/type/grafana_datasource_type_spec.rb
In order to support postgresql as datasource type I add support for specifying secure_json_data (which is needed when you setup a postgres datasource).
I removed the https datasource url-check again as it breaks the datasource check when postgres is used. ( fyi https://github.com/voxpupuli/puppet-grafana/pull/76)
=> Add postgres support and secure_json_data support

manifests/install.pp, spec/classes/grafana_spec.rb
Grafana upstream documetation: http://docs.grafana.org/installation/debian/, says to use 'stretch' codename for all repositories.
Update release codename from jessie to stretch, as per instructions at http://docs.grafana.org/installation/debian/.
N.B. This PR was tested on my own system, Debian 9 stretch. Could someone please check to see if older and other Ubuntu distributions will be affected by this change?
Fixes #112
=> Update release codename from jessie to stretch.

manifests/config.pp, manifests/init.pp
Add a file resource to config function.
Modified dependency slightly to allow plugins to be installed after file resource creates plugin directory: only works for package, repo, and archive install methods.
Fixes #79
=> Fix dependency in provisioning plugins

README.md, lib/puppet/provider/grafana_plugin/grafana_cli.rb, lib/puppet/type/grafana_plugin.rb, spec/acceptance/grafana_plugin_spec.rb, spec/classes/grafana_spec.rb, spec/unit/puppet/provider/grafana_plugin/grafana_cli_spec.rb, spec/unit/puppet/type/grafana_plugin_spec.rb
Adding the repo option to the grafana_cli plugin installation, so that it's possible to use a different repository e.g. a company internal server to install grafana plugins. As an example:
```puppet
grafana_plugin { 'grafana-simple-json-datasource':
ensure    => present,
repo => 'https://nexus.company.com/grafana/plugins',
}
```
n/a.
=> add --repo option to grafana_cli plugin install

lib/puppet/type/grafana_datasource.rb, spec/unit/puppet/type/grafana_datasource_type_spec.rb
- Puppet: 5
- Ruby: 2.4
- Distribution: CentOS
- Module version: master
```
grafana_datasource { 'PNP':
type             => 'sni-pnp-datasource',
...
}
```
```
Error: Failed to apply catalog: Parameter type failed on Grafana_datasource[PNP]: Invalid value "sni-pnp-datasource". Valid values are influxdb, elasticsearch, graphite, kairosdb, opentsdb, prometheus.
```
I have a custom Grafana plugin called 'sni-pnp-datasource' loaded into Grafana.  I'm thinking that specifying valid values of only the default plugins is too limiting, and proposing it be removed.
=> removing value restriction on grafana_datasource so any custom plugin can be used

README.md, lib/puppet/provider/grafana_notification/grafana.rb, lib/puppet/type/grafana_notification.rb, spec/unit/puppet/type/grafana_notification_type_spec.rb
This PR adds the ability to manage  notification channels (example.com/grafana/alerting/notifications) using the new ressource grafana_notification.
As others puppet-grafana resources, it uses Grafana API to manages them.
Applicable settings have been described in README.md.
Please note it is my first PR to VoxPopuli, I hope it does comply with all requested rules. If not, I will be happy to amend my work accordingly.
N/A
=> Integration notification channels

README.md, tasks/change_grafana_admin_password.json, tasks/change_grafana_admin_password.sh
The task will forcefully set the admin user's password and does not
require knowing the old password.
=> Add a task for setting the admin user's password

manifests/install.pp, spec/acceptance/class_spec.rb, spec/classes/grafana_spec.rb
This is necessary to fix the Travis CI pipeline.
Fixes #160 
Fixes #161 
Fixes #162 
Fixes #164
=> Fix version, because 6.0.0-beta1 does not exist anymore

manifests/install.pp, spec/classes/grafana_spec.rb
The subdirectory ```builds``` does not exist, which is not covered by the RSpec test. 
Fixes #85
=> Fix value of variable real_package_source

README.md
According to the Grafana documentation [0] the fields host, user and password are not applicable for the database type sqlite. I changed the example's database type to mysql for which these keys are valid.
[0]: http://docs.grafana.org/installation/configuration/#database
=> Corrected invalid database config example

README.md, lib/puppet/provider/grafana_folder/grafana.rb, lib/puppet/type/grafana_folder.rb, spec/acceptance/grafana_folder_spec.rb, spec/unit/puppet/type/grafana_folder_type_spec.rb
We found it useful to manage Grafana folders via Puppet. This type was heavily based on the code for `grafana_dashboard` type.
=> Implement grafana_folder resource type

data/family/FreeBSD.yaml, manifests/install.pp, metadata.json, spec/classes/grafana_spec.rb
We have everything to run this module on FreeBSD
using pkg/repo install_method.
It would be very nice to have this module available
for FreeBSD users ( no need to mark it as supported platform
in metadata.json )
Tested on: FreeBSD 12.0-RELEASE, FreeBSD 13-HEAD
=> Add FreeBSD 12 support

lib/puppet/provider/grafana_user/grafana.rb, lib/puppet/type/grafana_user.rb, spec/acceptance/grafana_user_spec.rb
This PR fixes the issue that on each puppet run the user password will be set.
As the grafana api does not provide any feature for that we try to connect as that user if login works we suppress the password change.
Fixes #104
=> Fix `grafana_user` `password` idempotency

lib/puppet/provider/grafana_conn_validator/net_http.rb, lib/puppet/type/grafana_conn_validator.rb, lib/puppet/type/grafana_dashboard.rb, lib/puppet/type/grafana_datasource.rb, lib/puppet/type/grafana_folder.rb, lib/puppet/type/grafana_notification.rb, lib/puppet/type/grafana_organization.rb, lib/puppet/type/grafana_plugin.rb, lib/puppet/type/grafana_user.rb, lib/puppet/util/grafana_conn_validator.rb, manifests/validator.pp, spec/acceptance/grafana_folder_spec.rb, spec/acceptance/grafana_plugin_spec.rb
Add a type that can verify the API is available before attempting to make API calls. Having autorequire on a service isn't enough. I've run into this already where service restarts but something like `grafana_folder` will try to use API before Grafana is ready.
This is nearly identical approach taken from PuppetDB module from Puppetlabs and Sensu's sensu module.
I made it opt-in by making a dedicated class for the validator to be included.  It won't make sense to opt-in to this by default until some improvements are made to DRY up the way `grafana_url` and duplicate items are passed to the various types.
=> Add mechanism to make API changes once API is available

README.md, lib/puppet/provider/grafana_dashboard_permission/grafana.rb, lib/puppet/provider/grafana_membership/grafana.rb, lib/puppet/provider/grafana_organization/grafana.rb, lib/puppet/provider/grafana_team/grafana.rb, lib/puppet/type/grafana_dashboard_permission.rb, lib/puppet/type/grafana_membership.rb, lib/puppet/type/grafana_organization.rb, lib/puppet/type/grafana_team.rb, spec/grafana_dashboard_permission_type_spec.rb, spec/grafana_membership_type_spec.rb, spec/unit/puppet/type/grafana_team_type_spec.rb
This pull request addresses the following concerns:
teams
Currently there is no support in this module for managing teams within an organization. Have added this type. Allows the home dashboard for team to be set / updated also.
organizations
To bring orgs in line with other resources - have updated this type so that orgs can be deleted. Couple of caveats to ensure predictability - default org "mainOrg." cannot be modified and if an organization is deleted, the orgnanization in use is returned to the default org.
dashboard permissions
I see another merge just now where the folder permissions were set on the folder itself. I am open to redoing the permissions as properties on a dashboard but I feel having permissions as a different type is easier to use and saves having to use hashes.
Able …
=> Support for teams, dashboard permissions and memberships

lib/puppet/type/grafana_ldap_config.rb
When running puppet generate types, the following error is raised:
```
Notice: Generating Puppet resource types.
Error: Failed to load custom type 'grafana_ldap_config' from '/etc/puppetlabs/code/environments/production/modules/grafana/lib/puppet/type/grafana_ldap_config.rb': uninitialized constant Puppet::Parameter::Boolean
```
Adding this require statement fix this issue.
n/a
=> Fix `puppet generate types`

manifests/config.pp, spec/classes/grafana_spec.rb
Handle case where `puppetsource` is not defined. The way I use this is I deploy my dashboards with a massive git repo and define lots of provisioning dashboards based on sub directories in that git repo by omitting `puppetsource`.
This is a continuation on #187
=> Don't manage dashboard path when puppetsource is not set

lib/puppet/type/grafana_dashboard_permission.rb, lib/puppet/type/grafana_membership.rb, lib/puppet/type/grafana_team.rb, spec/grafana_dashboard_permission_type_spec.rb, spec/grafana_membership_type_spec.rb, spec/unit/puppet/type/grafana_dashboard_type_spec.rb, spec/unit/puppet/type/grafana_folder_type_spec.rb, spec/unit/puppet/type/grafana_organization_type_spec.rb, spec/unit/puppet/type/grafana_team_type_spec.rb, spec/unit/puppet/type/grafana_user_type_spec.rb
Some newer API types did not get added with autorequires on Grafana_conn_validator so this gets those new types to have same autorequirement as other types to ensure the API is ready before executing API commands.
Add unit tests around grafana_conn_validator autorequires
=> Ensure all API types have grafana_conn_validator autorequires

lib/puppet/type/grafana_ldap_group_mapping.rb, lib/puppet/type/grafana_ldap_server.rb
Fix types to work with `puppet generate types`.  These are the errors being produced:
```
Jan 14 09:45:53 puppet0 r10k-postrun: #033[1;31mError: Failed to load custom type 'grafana_ldap_group_mapping' from '/etc/puppetlabs/code/environments/test_xdmod/modules/grafana/lib/puppet/type/grafana_ldap_group_mapping.rb': uninitialized constant Puppet::Parameter::Boolean#033[0m
Jan 14 09:45:54 puppet0 r10k-postrun: #033[1;31mError: Failed to load custom type 'grafana_ldap_server' from '/etc/puppetlabs/code/environments/test_xdmod/modules/grafana/lib/puppet/type/grafana_ldap_server.rb': uninitialized constant Puppet::Parameter::Boolean#033[0m
```
=> Fix types to work with 'puppet generate types'

README.md, lib/puppet/provider/grafana_plugin/grafana_cli.rb, lib/puppet/type/grafana_plugin.rb, spec/acceptance/class_spec.rb, spec/acceptance/grafana_plugin_spec.rb, spec/classes/grafana_spec.rb, spec/unit/puppet/provider/grafana_plugin/grafana_cli_spec.rb, spec/unit/puppet/type/grafana_plugin_spec.rb
This Pull Request is a continuation of  voxpupuli/puppet-grafana#217, which was in need of a rebase onto master since Aug 2020.
Fixes voxpupuli/puppet-grafana#173
Closes voxpupuli/puppet-grafana#217
=> Rebase plugin from zip patch

README.md, lib/puppet/provider/grafana_team/grafana.rb, lib/puppet/type/grafana_plugin.rb, lib/puppet/type/grafana_team.rb, spec/acceptance/class_spec.rb, spec/acceptance/grafana_team_spec.rb, spec/classes/grafana_spec.rb, spec/unit/puppet/provider/grafana_plugin/grafana_cli_spec.rb, spec/unit/puppet/type/grafana_plugin_spec.rb, spec/unit/puppet/type/grafana_team_type_spec.rb
In my environment we might have the dashboard `Node Metrics` in numerous folders with different user teams associated to each folder with slightly difference dashboards in each folder.  This change allows the team home dashboard to be selected by a specific folder rather than just picking the first dashboard that matches the name which might be the wrong dashboard in wrong folder and in my case would get permission denied for our users if wrong dashboard ended up matching the previous search logic that just looked for first dashboard to match a given name.
=> Allow grafana_team home dashboard to be scoped to a folder

metadata.json
While here, reorder FreeBSD entries.
=> Drop support for Debian 9, Ubuntu 16.04 (EOL)

README.md, lib/puppet/provider/grafana_dashboard/grafana.rb, spec/acceptance/grafana_folder_spec.rb
The grafana_dashboard function was changed from using the old deprecated api to the recommended endpoint using the uid. However, the module still passed the dashboard title to the API instead of the uid, always resulting in a dashboard not found error. This PR fixes the problem.
Fixes #261
=> Fix dashboard api call in grafana_dashboard

lib/puppet/provider/grafana.rb
This allows the HTTP operation PATCH required for resource type grafana_membership (https://github.com/voxpupuli/puppet-grafana/blob/master/lib/puppet/provider/grafana_membership/grafana.rb#L176). 
n/a
=> Add support for HTTP operation PATCH to fix grafana_membership

manifests/config.pp
This is what the package has by default. Since grafana can still read the file, this should not be an issue.
I noticed that after an apt upgrade Puppet changed the owner again. This prevents needsless restarts.
=> Set grafana.ini owner to root with packages

README.md, lib/puppet/provider/grafana_dashboard_permission/grafana.rb, lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/type/grafana_user.rb, manifests/config.pp, manifests/init.pp, spec/classes/grafana_spec.rb
Useful when your configuration contains passwords you don't want to
expose in your puppet logs and reports.
=> Accept `Sensitive` `cfg`

README.md
This hasn't been the case since Puppet 3.
=> Remove outdated `Integer note` from README

README.md, manifests/config.pp, manifests/init.pp, spec/classes/grafana_spec.rb
Similar to 04fcd9111a17535853623da4c14f73b84407c4a9 this commit adds
support for `Sensitive` to the `ldap_cfg` parameter.
I've also fixed the LDAP examples `email` attibute to be `mail` which
is correct for Active Directory (where `username` is `sAMAccountName`)
=> Accept `Sensitive` `ldap_cfg`

lib/puppet/provider/grafana_user/grafana.rb, lib/puppet/type/grafana_user.rb, spec/acceptance/grafana_user_spec.rb
Previously `save_user` was being called once per changed property and
calls were also being made to update user properties, password and the
admin flag regardless of whether these properties needed updating.
Using `flush` is more efficient.
* `full_name` is fixed (it was previously a parameter instead of a property).
* When a user is created, `is_admin` is correctly set in a single Puppet run.
* Properties can be managed individually.
* Instead of making `password` mandatory, (when creating a user), if
`password` isn't specified, a random one is used.
Fixes #121
=> Fix `grafana_user` and switch to using `flush`

lib/puppet/provider/grafana_user/grafana.rb, spec/acceptance/grafana_user_spec.rb
Previously, the number of API calls to look up the details of a single user was equal to `1 + the number of existing users`.
This made managing multiple users exponentially slow.
The way the types in this module are written, (with the Grafana API user credentials being parameters of each resource), we can't implement `prefetch` to fetch all users just once; but we can change the implementation to directly lookup the user we're trying to manage.
This is _much_ faster!
=> Fix performance of `grafana_user`

metadata.json
This disables testing on Arch Linux. The acceptance tests never worked.
The goal is to merge this PR, rebase the modulesync PR and merge it,
afterwards create a new PR which readds Arch Linux and fixes the tests.
=> Disable Arch Linux testing

data/common.yaml, data/family/Debian.yaml, data/family/RedHat.yaml, manifests/init.pp, manifests/install.pp
* Added support for custom repository URL
* moved hard coded values to variables
* added documentation
=> Add support for custom repository URL

lib/puppet/provider/grafana_datasource/grafana.rb, lib/puppet/type/grafana_datasource.rb, lib/puppet/type/grafana_folder.rb, spec/acceptance/grafana_datasource_spec.rb, spec/support/acceptance/supported_versions.rb
Refactor `grafana_datasource`
Property defaults are removed from the type and where values are needed
on datasource creation, the defaults are in the provider.
If updating an existing datasource, only properties that you want to
manage have to be specified. The API needs the post to contain several
more fields, but these can be pulled from the existing state.
`uid` is added as an optional property and, (in versions that support
it), is used when updating a datasource, (instead of updating by `id`
which has been deprecated.)
Fetching and deleting datasources by `id` has also been deprecated in
Grafana 9 so is replaced by fetching and deleting by `name`.
The managing of multiple datasources is now quicker as the previous
implementation made a number of API calls that grew exponentially with …
=> Refactor `grafana_datasource` and add `uid` property

.msync.yml, Gemfile, data/family/Debian.yaml, manifests/init.pp
According to https://packages.grafana.com/:
> The GPG key used to sign the APT repository (fingerprint
> 4E40DDF6D76E284A4A6780E48C8C34C524098CB6) was rotated on 2023-01-12 and
> replaced with a new key with fingerprint
> 0E22EB88E39E12277A7760AE9E439B102CF3C0C6.
Update the key accordingly.
=> Fix default PGP key

spec/acceptance/class_spec.rb, spec/support/acceptance/supported_versions.rb
These packages are currently not available.
Also include:
* #312
* #311
=> Disable beta packages tests on Debian

metadata.json, spec/acceptance/class_spec.rb
=> puppet/archive: Allow 7.x; puppetlabs/stdlib: Require 9.x

REFERENCE.md, data/family/Debian.yaml, manifests/init.pp
Following [apt.grafana.com](https://apt.grafana.com/), repo signing key were rotated
No issue associated
=> Update Debian repo signing key

lib/puppet/provider/grafana_team/grafana.rb, lib/puppet/type/grafana_folder.rb, spec/acceptance/grafana_folder_spec.rb, spec/acceptance/grafana_team_spec.rb, spec/acceptance/grafana_user_spec.rb, spec/support/acceptance/supported_versions.rb
Fix #318
Appears the team preferences required home folder UID and not ID.  The docs are incorrect on Grafana's website it seems
=> Support Grafana 10.x

lib/puppet/provider/grafana_team/grafana.rb, spec/acceptance/grafana_datasource_spec.rb, spec/acceptance/grafana_team_spec.rb, spec/classes/grafana_spec.rb, spec/support/acceptance/supported_versions.rb
=> CI: Run on latest grafana patch versions

spec/support/acceptance/prepare_host.rb
We didn't clean up all leftovers between aceptance tests in the past, this can hide errors.
=> CI: Enhance cleanup script

REFERENCE.md, data/family/FreeBSD.yaml, manifests/config.pp, manifests/init.pp, spec/acceptance/class_spec.rb, spec/classes/grafana_spec.rb
The tests are not failing @bastelfreak and me are thinks that a test task already created the folders.
but if you ran an basic example on a real machine you will get:
```
Could not set 'file' on ensure: No such file or directory - A directory component in /etc/grafana/provisioning/datasources/puppetprovisioned.yaml20240607-2077526-prxolk.lock does not exist or is a dangling symbolic link (file: …/grafana/manifests/config.pp, line: 164)
Wrapped exception:
No such file or directory - A directory component in /etc/grafana/provisioning/datasources/puppetprovisioned.yaml20240607-2077526-prxolk.lock does not exist or is a dangling symbolic link
```
after a look into that system the /etc/grafana/provisioning/datasources/ doesn't exists.
this PR should fix that and create the folder
=> Create subpaths for provisioning_datasources

README.md
=> README.md: Clarify toml gem setup
