voxpupuli/puppet-grafana

.rubocop.yml, lib/puppet/provider/grafana_datasource/grafana.rb
I'm not sure if this provider has ever worked or just got broken in a previous merge, but i found several issues with it.
- missing and malformed arguments to `send_request` method
- methods `default` do not match the parameter name `is_default`
=> fix datasource provider

CHANGELOG.md
this includes our changes since the fork
=> Add changelog entries for changes since 2.5.0

CHANGELOG.md, metadata.json
=> release 2.6.1

manifests/install.pp, spec/classes/grafana_spec.rb
Replaces a hardcoded value which is no more relevant for a newer EL distributions.
=> Use operatinsystemmajrelease fact in repo url

manifests/install.pp, manifests/params.pp, metadata.json, spec/classes/grafana_spec.rb
=> Add support for archlinux

.github/CONTRIBUTING.md, .msync.yml, .overcommit.yml, .rubocop.yml, .travis.yml, Gemfile, spec/classes/grafana_spec.rb, spec/unit/puppet/type/grafana_dashboard_type_spec.rb, spec/unit/puppet/type/grafana_datasource_type_spec.rb
=> Modulesync 0.21.0

.gitignore, .msync.yml, .rspec_parallel, .rubocop.yml, Gemfile, spec/acceptance/nodesets/archlinux-2-x64.yml, spec/acceptance/nodesets/docker/ubuntu-16.04.yml, spec/spec_helper_acceptance.rb
=> modulesync 0.21.3

metadata.json
=> Support newer versions of puppetlabs/apt module

README.md, lib/puppet/provider/grafana_user/grafana.rb, lib/puppet/type/grafana_user.rb, spec/unit/puppet/type/grafana_user_type_spec.rb
Basic support for grafana global user management.
=> grafana_user custom resource

metadata.json
=> add debian 8 and 9 support

metadata.json
=> bump archive upper boundary to work with latest versions

manifests/install.pp, manifests/params.pp
=> switch from topscope facts to $facts hash

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .msync.yml, Gemfile, spec/acceptance/nodesets/docker/ubuntu-16.04.yml
=> modulesync 1.9.1

CHANGELOG.md, metadata.json
=> release 4.3.0

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/grafana_spec.rb
This PR adds two new parameters sysconfig_location and sysconfig to manage the environment files which come with the RPM and DEB packages.
=> Manage sysconfig files

metadata.json
=> bump archive upper version boundary to <4.0.0

CHANGELOG.md, metadata.json
=> release 4.4.1

CHANGELOG.md, metadata.json
=> release 4.5.0

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/acceptance/class_spec.rb
This PR adds the capacity to specify the target file for provisioning files. Allowing it to adapt easily to different Grafana deployments and providing a way to create placeholder files.
=> Parametrize provisioning file names

README.md, manifests/init.pp, manifests/params.pp, spec/acceptance/class_spec.rb, spec/classes/grafana_spec.rb
Change default of version parameter to 'installed'
Fixes GH-125.
=> Change default of version parameter to 'installed'

.msync.yml, Gemfile, spec/classes/coverage_spec.rb, spec/default_facts.yml, spec/spec_helper.rb
=> modulesync 2.2.0

manifests/config.pp, spec/classes/grafana_spec.rb
Archive install_method must creates data_dir.
Use format:
Fixes #142
=> archive install_method creates data_dir

manifests/config.pp
=> replace deprecated has_key() with `in`

manifests/install.pp
Fixes #152 
Available architectures : https://grafana.com/grafana/download?platform=linux
=> Fix #152 : multi arch send out a notice

manifests/init.pp, manifests/install.pp, spec/acceptance/class_spec.rb
Along with the APT repo update (#150), the repo name seems to have changed from `testing` to `beta` for beta releases.
See http://docs.grafana.org/installation/debian/#apt-repository
I haven't created an issue.
=> Update repo_name Enum for new 'beta' repo

examples/init.pp, manifests/install.pp
=> include classes without leading ::

manifests/install.pp, spec/classes/grafana_spec.rb
According to the official website, the source of archives and packages has changed. 
Use format:
Fixes #85
=> Fix value of variables base_url and real_archive_source

lib/puppet/type/grafana_datasource.rb, lib/puppet/type/grafana_user.rb
Fixes #82
An alternative to https://github.com/voxpupuli/puppet-grafana/pull/162
=> Mark passwords as sensitive

.msync.yml, .travis.yml, Gemfile, Rakefile, spec/spec_helper.rb, spec/unit/puppet/provider/grafana_plugin/grafana_cli_spec.rb
=> modulesync 2.7.0

README.md, lib/puppet/provider/grafana_dashboard/grafana.rb, lib/puppet/provider/grafana_folder/grafana.rb, lib/puppet/type/grafana_dashboard.rb, spec/acceptance/grafana_folder_spec.rb
After implementing the `grafana_folder` resource, it became apparent that updating the `grafana_dashboard` resource to take advantage of folders would be a critical second step in the implementation.
=> Update grafana_dashboard resource for folders

README.md
Add explanations on how to provision dashboards coming from Grafana.com
=> DOC Add Provisioning with dashboards from grafana.com

manifests/config.pp, manifests/init.pp
Avoids restarts of grafana when provisioned dashboards change.
=> Do not restart grafana on provisioned dashboard updates

README.md
Minor Doc correction for grafana_folder
Fixes #197
=> #197 Minor Doc correction - grafana_folder

lib/puppet/provider/grafana_folder/grafana.rb, lib/puppet/type/grafana_folder.rb, spec/acceptance/grafana_folder_spec.rb
Add `permissions` property to `grafana_folder` type so that folder permissions can be managed.
=> Support managing folder permissions

manifests/service.pp
=> Clean up code, because params.pp has been removed

README.md, lib/puppet/provider/grafana_dashboard/grafana.rb, lib/puppet/provider/grafana_team/grafana.rb, lib/puppet/type/grafana_team.rb, spec/acceptance/grafana_team_spec.rb
Have come across a bug in grafana_teams where defaults are not being set for organization and home_dashboard - have updated these. 
A couple of updated examples for the README also.
Will add acceptance tests here once I figure out how to run them :) I'm new to beaker.
=> Bugfix for teams, update README and acceptance testing

metadata.json
=> Drop Eol CentOS 6 support

manifests/config.pp
Add possibility to use multiple puppetsource for provisioned dashboard by default.
Fixes #130
=> Allow multiple puppetsource

data/family/FreeBSD.yaml
Latest current version: www/grafana7
=> bump default grafana version for FreeBSD

lib/puppet/provider/grafana_dashboard/grafana.rb, spec/acceptance/class_spec.rb, spec/acceptance/grafana_folder_spec.rb, spec/acceptance/grafana_plugin_spec.rb, spec/acceptance/grafana_team_spec.rb, spec/acceptance/grafana_user_spec.rb, spec/support/acceptance/prepare_host.rb, spec/support/acceptance/supported_versions.rb
This change is backwards incompatible for Grafana versions prior to 6.0
=> Support only 6.x/7.x/8.x versions

.editorconfig, .github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .msync.yml, .overcommit.yml, .pmtignore, .rspec, .rspec_parallel, .rubocop.yml, .yardopts, Dockerfile, Gemfile, Rakefile, spec/spec_helper.rb, spec/spec_helper_acceptance.rb
=> Modulesync 4.1.0

metadata.json
=> Add Ubuntu 20.04 support

README.md
=> Update README.md about tested OSes

CHANGELOG.md, README.md, REFERENCE.md, metadata.json
=> Release 9.0.0

metadata.json
=> Add support for Debian 11, CentOS 8, RedHat 8 and FreeBSD 13

.github/workflows/ci.yml, .msync.yml, Gemfile
=> modulesync 4.3.0

README.md
Correct the type in the example output.
=> Correct type for the example

README.md, lib/puppet/provider/grafana_user/grafana.rb, lib/puppet/type/grafana_user.rb, spec/acceptance/grafana_user_spec.rb, spec/unit/puppet/type/grafana_user_type_spec.rb
=> Add `organizations` property to `grafana_user`

.github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .msync.yml, Dockerfile, Gemfile, spec/setup_acceptance_node.pp, spec/spec_helper.rb
=> modulesync 5.3.0

CHANGELOG.md, REFERENCE.md, manifests/init.pp, metadata.json
=> Release 11.0.0

README.md
=> Update the link to the toml gem

.github/SECURITY.md, .gitignore, .puppet-lint.rc, .sync.yml, Gemfile, REFERENCE.md, Rakefile, manifests/init.pp
=> modulesync 5.4.0

.github/SECURITY.md, .gitignore, .puppet-lint.rc, .sync.yml, Gemfile, REFERENCE.md, Rakefile, manifests/init.pp, metadata.json
Contains https://github.com/voxpupuli/puppet-grafana/pull/311 and #310
=> Add AlmaLinux 8 support

.github/SECURITY.md, .gitignore, .puppet-lint.rc, .sync.yml, Gemfile, REFERENCE.md, Rakefile, manifests/init.pp, metadata.json
also contains https://github.com/voxpupuli/puppet-grafana/pull/310
=> Add Rocky 8 support

.github/CONTRIBUTING.md, .msync.yml, .sync.yml, Gemfile, spec/acceptance/class_spec.rb, spec/spec_helper_acceptance.rb
=> modulesync 6.0.0

.github/CONTRIBUTING.md, .msync.yml, .sync.yml, Gemfile, metadata.json, spec/acceptance/class_spec.rb, spec/spec_helper_acceptance.rb
=> Add puppet 8 support

CHANGELOG.md, metadata.json
=> Release 13.1.0

metadata.json, spec/setup_acceptance_node.pp
=> Drop EoL Ubuntu 18.04 support

metadata.json
=> Drop EoL RedHat 7, CentOS 7 & 8 support

lib/puppet/provider/grafana_team/grafana.rb, spec/acceptance/grafana_datasource_spec.rb, spec/acceptance/grafana_team_spec.rb, spec/classes/grafana_spec.rb, spec/support/acceptance/supported_versions.rb
=> Drop support for EoL Grafana 8 & 9

manifests/install.pp
Use modern apt keyring for the Debian apt repo setup
=> Use modern apt keyrings

.github/CONTRIBUTING.md, .github/labeler.yml, .github/release.yml, .github/workflows/ci.yml, .github/workflows/labeler.yml, .github/workflows/prepare_release.yml, .github/workflows/release.yml, .msync.yml, .pmtignore, .puppet-lint.rc, .sync.yml, Gemfile, manifests/install.pp, spec/classes/grafana_spec.rb, spec/spec_helper.rb
=> modulesync 9.5.0
